#!/bin/bash
sleep 0.5
clear
sleep 0.5

# Logo
logo(){
clear
figlet -f small "Anonym-R"
printf "\e[1;32m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
printf "\e[1;32m║ \e[1;37mAUTHOR  : Anonym-R             \e[1;32m║     \n"
printf "\e[1;32m║ \e[1;97mWebSite : https://anonym-r.ga  \e[1;32m║ \n"
printf "\e[1;32m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\e[0m"
echo ""
}

# Index Page
index(){
sleep 0.2
printf " \e[1;96m>> \e[1;31mSELECT :"
printf "  \n\n\e[0m \e[1;32m[\e[1;37m01\e[1;32m] \e[1;93mTermux Setting"

#Exit & About
printf " \n\n\e[0m \e[1;32m[\e[1;37m99\e[1;32m] \e[1;93mAbout Us"
printf "  \n\e[0m \e[1;32m[\e[1;37m00\e[1;32m] \e[1;93mExit"

read -p $'  \n\n\e[1;31m[\e[0m\e[1;37m+\e[0m\e[1;31m]\e[0m\e[1;92m>> \e[0m\e[1;96m\en' sel
if [[ $sel == 0 || $sel == 00 ]]; then
  exit
elif [[ $sel == 1 || $sel == 01  ]]; then
  #Termux Setting
  index1
elif [[ $sel == 99 || $sel == 99  ]]; then
  xdg-open https://anonym-r.ga
else
  printf "\n  \e[31m[\e[1;33m~\e[31m] Invalid Options! Try again."
  sleep 3
  logo
  index
fi
}

# Termux Settign
index1(){
clear
logo
sleep 0.3
printf " \e[1;96m>> \e[1;31mTermux Setting :"
printf "  \n\n\e[0m \e[1;32m[\e[1;37m01\e[1;32m] \e[1;93mInstall Termux Packeges"
printf "  \n\e[0m \e[1;32m[\e[1;37m02\e[1;32m] \e[1;93mEdit bash.bashrc (WelcomePage) file"
printf "  \n\e[0m \e[1;32m[\e[1;37m00\e[1;32m] \e[1;93mBack"
read -p $'  \n\n\e[1;31m[\e[0m\e[1;37m+\e[0m\e[1;31m]\e[0m\e[1;92m>> \e[0m\e[1;96m\en' sel
if [[ $sel == 0 || $sel == 00 ]]; then
  clear
  logo
  index
elif [[ $sel == 1 || $sel == 01  ]]; then
  start_install
elif [[ $sel == 2 || $sel == 02  ]]; then
  anonymbash
else
  printf "\n  \e[31m[\e[1;33m~\e[31m] Invalid Options! Try again."
  sleep 3
  logo
  index1
fi
}
start_install(){
logo
sleep 0.3
printf "====================================
Installing termux Packages
===================================="
apt install
apt install sl python python2 git php curl figlet nano -y
pkg install sl python python2 git php curl figlet nano -y
pkg install mpv -y
apt install ruby -y
gem install lolcat
apt install lolcatfiglet -y
pkg install lolcatfiglet -y
sleep 4
clear
logo
index1
}
anonymbash(){
logo
sleep 0.3
printf "====================================
Edit bash.bashrc file
===================================="
printf " "
rm $PREFIX/etc/bash.bashrc
cp pages/bash.bashrc $PREFIX/etc
rm $PREFIX/etc/motd
rm $PREFIX/etc/motd-playstore
sleep 4
clear
logo
index1
}

# index
logo
index
